import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: '#faf8f5' },
    header: {
        padding: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#e9dcc9',
        backgroundColor: '#faf8f5',
    },
    headerTitle: { fontSize: 18, fontWeight: '600', textAlign: 'center', color: '#333' },
    content: { paddingHorizontal: 16, paddingBottom: 40 },
    profileContainer: { marginTop: 16, marginBottom: 24 },
    profileInner: {
        backgroundColor: '#fff',
        borderRadius: 16,
        padding: 16,
        flexDirection: 'row',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOpacity: 0.05,
        shadowRadius: 8,
        borderWidth: 1,
        borderColor: 'rgba(0,0,0,0.05)',
    },
    avatar: { width: 64, height: 64, borderRadius: 32 },
    onlineDot: {
        position: 'absolute',
        bottom: 4,
        right: 4,
        width: 12,
        height: 12,
        backgroundColor: '#4CAF50',
        borderRadius: 6,
        borderWidth: 2,
        borderColor: '#fff',
    },
    profileText: { flex: 1, marginLeft: 12 },
    profileNameRow: { flexDirection: 'row', alignItems: 'center' },
    profileName: { fontSize: 16, fontWeight: '600', color: '#333' },
    editButton: {
        backgroundColor: '#f5eee6',
        padding: 6,
        borderRadius: 6,
        marginLeft: 8,
    },
    profileMessage: { fontSize: 12, color: '#777', marginTop: 4 },
    section: { marginBottom: 24 },
    sectionTitle: { fontSize: 13, fontWeight: '600', color: '#666', marginBottom: 8 },
    itemButton: {
        backgroundColor: '#fff',
        borderRadius: 12,
        padding: 12,
        marginBottom: 12,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOpacity: 0.02,
        shadowRadius: 4,
        borderWidth: 1,
        borderColor: 'rgba(0,0,0,0.03)',
    },
    itemInner: {
        flex: 1,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    itemLeft: { flexDirection: 'row', alignItems: 'center' },
    iconWrapper: {
        width: 40,
        height: 40,
        backgroundColor: '#f5eee6',
        borderRadius: 10,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    // Removed flex: 1 from textWrapper to prevent overflow
    textWrapper: {},
    itemTitle: { fontSize: 14, fontWeight: '500', color: '#333' },
    itemSubtitle: { fontSize: 11, color: '#777', marginTop: 2 },
    itemRight: { flexDirection: 'row', alignItems: 'center', },
    logoutButton: {
        backgroundColor: '#ffecec',
        borderRadius: 12,
        padding: 14,
        alignItems: 'center',
        marginTop: 16,
    },
    logoutInner: { flexDirection: 'row', alignItems: 'center' },
    logoutText: { fontSize: 14, fontWeight: '500', color: '#FF4D4F', marginLeft: 8 },
    switchContainer: {
        width: 40,
        height: 24,
        borderRadius: 12,
        justifyContent: "center",
        paddingHorizontal: 4,
    },
    switchCircle: {
        width: 18,
        height: 18,
        borderRadius: 9,
        backgroundColor: "#fff",
        shadowColor: "#000",
        shadowOpacity: 0.05,
        shadowRadius: 2,
    },
});
